version: '3.8'

services:
  postgres:
    environment:
      POSTGRES_DB: resume_builder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    command: redis-server --appendonly yes

  nats:
    command: [ "nats-server", "--jetstream", "--store_dir", "/data" ]

  minio:
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
